#ifndef LWPKT_OPTS_H
#define LWPKT_OPTS_H

#define LWPKT_CFG_MAX_DATA_LEN 64
#define LWPKT_CFG_USE_ADDR     LWPKT_OFF
#define LWPKT_CFG_USE_FLAGS    LWPKT_OFF
#define LWPKT_CFG_USE_CMD      LWPKT_ON_STATIC
#define LWPKT_CFG_USE_CRC      LWPKT_ON_STATIC
#define LWPKT_CFG_CRC32        LWPKT_OFF
#define LWPKT_CFG_USE_EVT      LWPKT_ON_STATIC

#endif /* LWPKT_OPTS_H */
