#ifndef USB_DESCRIPTORS_H
#define USB_DESCRIPTORS_H
#define USB_CDC_EP_NOTIFY 0x81U
#define USB_CDC_EP_OUT 0x02U
#define USB_CDC_EP_IN 0x82U
#define USB_CDC_VENDOR_ID 0xCAFEU
#define USB_CDC_PRODUCT_ID 0x4001U
#endif
