# Portable modules shared by firmware and native tests.
get_filename_component(ROBOT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(ROBOT_MIDDLEWARE "${ROBOT_ROOT}/middleware")
add_library(wheel_test_core STATIC "${ROBOT_MIDDLEWARE}/diagnostics/src/wheel_test.c")
target_include_directories(wheel_test_core PUBLIC "${ROBOT_MIDDLEWARE}/diagnostics/include")
add_library(robot_contracts INTERFACE)
target_include_directories(robot_contracts INTERFACE "${ROBOT_MIDDLEWARE}/contracts/include")
add_library(balance_core STATIC "${ROBOT_MIDDLEWARE}/control/src/balance_controller.c"
    "${ROBOT_MIDDLEWARE}/control/src/safety_fsm.c" "${ROBOT_MIDDLEWARE}/control/src/balance_runtime.c")
target_include_directories(balance_core PUBLIC "${ROBOT_MIDDLEWARE}/control/include")
target_link_libraries(balance_core PUBLIC robot_contracts m)
add_library(parameters_core STATIC "${ROBOT_MIDDLEWARE}/parameters/src/parameter_profile.c"
    "${ROBOT_MIDDLEWARE}/parameters/src/parameter_store.c")
target_include_directories(parameters_core PUBLIC "${ROBOT_MIDDLEWARE}/parameters/include")
target_link_libraries(parameters_core PUBLIC balance_core)
add_library(encoder_core STATIC "${ROBOT_MIDDLEWARE}/encoder/src/encoder_counter.c")
target_include_directories(encoder_core PUBLIC "${ROBOT_MIDDLEWARE}/encoder/include")
add_library(monotonic_clock STATIC "${ROBOT_MIDDLEWARE}/timebase/src/monotonic_clock.c")
target_include_directories(monotonic_clock PUBLIC "${ROBOT_MIDDLEWARE}/timebase/include")
set(FUSION_SOURCE "${ROBOT_MIDDLEWARE}/mpu6050/third_party/fusion")
add_library(fusion_vendor STATIC "${FUSION_SOURCE}/FusionAhrs.c" "${FUSION_SOURCE}/FusionBias.c"
    "${FUSION_SOURCE}/FusionConvention.c" "${FUSION_SOURCE}/FusionRemap.c")
target_include_directories(fusion_vendor PUBLIC "${FUSION_SOURCE}")
target_compile_definitions(fusion_vendor PUBLIC FUSION_USE_NORMAL_SQRT)
target_link_libraries(fusion_vendor PUBLIC m)
add_library(imu_fusion_core STATIC "${ROBOT_MIDDLEWARE}/mpu6050/src/imu_fusion.c")
target_include_directories(imu_fusion_core PUBLIC "${ROBOT_MIDDLEWARE}/mpu6050/include")
target_link_libraries(imu_fusion_core PUBLIC robot_contracts PRIVATE fusion_vendor)
set(SERIAL_SOURCE "${ROBOT_MIDDLEWARE}/serial")
add_library(lwrb STATIC "${SERIAL_SOURCE}/third_party/lwrb/src/lwrb/lwrb.c")
target_include_directories(lwrb PUBLIC "${SERIAL_SOURCE}/third_party/lwrb/src/include")
add_library(lwpkt STATIC "${SERIAL_SOURCE}/third_party/lwpkt/src/lwpkt/lwpkt.c")
target_include_directories(lwpkt PUBLIC "${SERIAL_SOURCE}/third_party/lwpkt/src/include" "${SERIAL_SOURCE}/include")
target_link_libraries(lwpkt PUBLIC lwrb)
add_library(serial_codec STATIC "${SERIAL_SOURCE}/src/serial_codec.c")
target_include_directories(serial_codec PUBLIC "${SERIAL_SOURCE}/include")
add_library(protocol_engine STATIC "${SERIAL_SOURCE}/src/serial_protocol_engine.c")
target_link_libraries(protocol_engine PUBLIC serial_codec lwpkt lwrb)
add_library(robot_port_api INTERFACE)
target_include_directories(robot_port_api INTERFACE "${ROBOT_ROOT}/platform/include"
    "${ROBOT_MIDDLEWARE}/motor/include" "${ROBOT_MIDDLEWARE}/encoder/include" "${ROBOT_MIDDLEWARE}/mpu6050/include")
